services:
  - type: web
    name: futbol-league-backend
    plan: free
    region: frankfurt
    buildCommand: npm ci --omit=dev && npm run build
    startCommand: npm run start
    autoDeploy: true
    branch: main
    rootDirectory: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false

  - type: static
    name: futbol-league-frontend
    plan: free
    region: frankfurt
    buildCommand: npm ci --omit=dev && npm run build
    publishPath: dist
    autoDeploy: true
    branch: main
    rootDirectory: frontend
    env:
      - key: VITE_BACKEND_URL
        value: "https://futbol-league-backend.onrender.com"

databases:
  - name: obnliga-db
    plan: free
    region: frankfurt
    type: postgres

  - name: obnliga-redis
    plan: free
    region: frankfurt
    type: redis