services:
  - type: web
    name: OBNBEK
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: "cd backend && npm install && npm run build && npx prisma generate --schema ../prisma/schema.prisma && npx prisma migrate deploy --schema ../prisma/schema.prisma"
    autoDeployTrigger: commit
    branch: main
    envVars:
      - key: DATABASE_URL
        value: "postgresql://football_obn_ztbb_user:zSGQTTZlgi0GCL05Zto5FENhdaSqrdXP@dpg-d3ckliq4d50c73cl4eeg-a.frankfurt-postgres.render.com/football_obn_ztbb?sslmode=require"
      - key: REDIS_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    startCommand: "cd backend && npx prisma generate --schema ../prisma/schema.prisma && npm run start"

  - type: web
    name: OBNFRONT
    runtime: static
    plan: free
    region: frankfurt
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
    autoDeployTrigger: commit
    branch: main
    envVars:
      - key: VITE_BACKEND_URL
        value: "https://OBNBEK.onrender.com"