version: 1

services:
  - type: web
    name: futbol-league-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: "cd backend && npm install && npm run build && npx prisma generate --schema ../prisma/schema.prisma && npx prisma migrate deploy --schema ../prisma/schema.prisma"
    autoDeployTrigger: commit
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: obnliga-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: obnliga-redis
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    startCommand: "cd backend && npx prisma generate --schema ../prisma/schema.prisma && npm run start"

  - type: static
    name: futbol-league-frontend
    plan: free
    region: frankfurt
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
    autoDeployTrigger: commit
    branch: main
    envVars:
      - key: VITE_BACKEND_URL
        value: "https://futbol-league-backend.onrender.com"

databases:
  - name: obnliga-db
    plan: free
    region: frankfurt
    type: postgres

  - name: obnliga-redis
    plan: free
    region: frankfurt
    type: redis