export const PREDICTION_UPCOMING_DEFAULT_DAYS = 6
export const PREDICTION_UPCOMING_MAX_DAYS = 10
export const PREDICTION_UPCOMING_CACHE_TTL_SECONDS = 300
export const PREDICTION_UPCOMING_STALE_SECONDS = 120
export const PREDICTION_USER_CACHE_TTL_SECONDS = 300
export const PREDICTION_USER_STALE_SECONDS = 120
export const PREDICTION_MAX_SELECTION_LENGTH = 64

export const PREDICTION_DEFAULT_TOTAL_LINE = 2.5
export const PREDICTION_TOTAL_LOOKBACK_MATCHES = 5
export const PREDICTION_TOTAL_MIN_SAMPLE_SIZE = 3
export const PREDICTION_TOTAL_MIN_LINE = 0.5
export const PREDICTION_TOTAL_MAX_LINE = 6.5

export const PREDICTION_MATCH_OUTCOME_BASE_POINTS = 10
export const PREDICTION_TOTAL_GOALS_BASE_POINTS = 12

export const ACTIVE_PREDICTION_CACHE_KEY = (days: number) => `predictions:list:${days}`
export const USER_PREDICTION_CACHE_KEY = (userId: number) => `predictions:user:${userId}`
